package fullyadjustableskills.skills;

import com.fs.starfarer.api.characters.ShipSkillEffect;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;

public class FASEnergyWeaponMastery {
    public static float FLUX_COST_MULT = 0.10f;

    public static class Level2 implements ShipSkillEffect {
        public void apply(MutableShipStatsAPI stats, ShipAPI.HullSize hullSize, String id, float level) {
            stats.getEnergyWeaponFluxCostMod().modifyMult(id, 1f - FLUX_COST_MULT);
        }

        public void unapply(MutableShipStatsAPI stats, ShipAPI.HullSize hullSize, String id) {
            stats.getEnergyWeaponFluxCostMod().unmodify(id);
        }

        public String getEffectDescription(float level) {
            return "-" + Math.round(FLUX_COST_MULT * 100f) + "% flux generated by energy weapons";
        }

        public String getEffectPerLevelDescription() {
            return null;
        }

        public ScopeDescription getScopeDescription() {
            return ScopeDescription.PILOTED_SHIP;
        }

    }
}
